var Car = 'farrari';
console.log("Is car == 'subaru'? I predict True.");
console.log(Car == 'farrari');
var wheather = 'rainy';
console.log("Is wheather =='rainy'? I pridict True");
console.log(wheather == 'rainy');
var Day = 'Friday';
console.log("Is Day =='Friday'? I pridict False");
console.log(Day == 'Friday');
var Name = 'Usman';
console.log("Is name =='Usman'? I pridict True");
console.log(Name == 'usman');
var age = '16';
console.log("Is age =='16'? I pridict True");
console.log(age == '16');
var level = 'school';
console.log("Is level =='school'? I pridict False");
console.log(level == 'schoool');
var bike = 'honda';
console.log("Is bike =='honda'? I pridict False");
console.log(bike == 'hnda');
var city = 'pakistan';
console.log("Is city =='pakistan'? I pridict true");
console.log(city == 'pakiStan');
var country = 'karachi';
console.log("Is country =='kaRachi'? I pridict True");
console.log(country == 'karachi');
var Wheather = 'sunny';
console.log("Is Weather =='sunny'? I pridict True");
console.log(Wheather == 'suny');
