var locations = ['Tajmahal', 'Baali', 'Turkey', 'South Island', 'London'];
console.log("Original order:");
console.log(locations);
console.log("\nAlphabetical:");
console.log("sorted(locations)");
console.log("\nOriginal order:");
console.log(locations);
console.log("\nReverse alphabetical:");
console.log("sorted " + locations, " reverse=True");
console.log("\nOriginal order:");
console.log(locations);
console.log("\nReversed:");
locations.reverse();
console.log(locations);
console.log("\nOriginal order:");
locations.reverse();
console.log(locations);
console.log("\nAlphabetical");
locations.sort();
console.log(locations);
console.log("\nReverse alphabetical");
locations.sort();
console.log(locations);
