let friends: Array<string> = ["Naveed", "Husain", "Hashim", "Saud", "Sameer"];
friends[1] = "Naveed";
friends[2] = "Husain";
friends[3] = "Hashim";
friends[4] = "Saud";
friends[5] = "Sameer";
console.log("very kindly and brave boy is "+ friends[1]);
console.log("very kindly and brave boy is "+ friends[2]);
console.log("very kindly and brave boy is "+ friends[3]);
console.log("very kindly and brave boy is "+ friends[4]);
console.log("very kindly and brave boy is "+ friends[5]);