var friends = ["Asad", "Ali", "Moiz",];
friends[1] = "Asad";
console.log("How are you bro today is my birthday and i arranged a party and you are invited. i hope you are coming in my party  " + friends[1]);
friends[2] = "Ali";
console.log("How are you bro today is my birthday and i arranged a party and you are invited. i hope you are coming in my party " + friends[2]);
friends[3] = "Moiz";
console.log("How are you bro today is my birthday and i arranged a party and you are invited. i hope you arecoming in my party " + friends[3]);
friends[3] = "Moiz";
console.log("Sorry " + friends[3] + " can't make it dinner");
var friend = "Huzefa";
friends[1] = "Asad";
console.log("How are you bro today is my birthday and i arranged a party and you are invited. i hope you are coming in my party  " + friends[1]);
friends[2] = "Ali";
console.log("How are you bro today is my birthday and i arranged a party and you are invited. i hope you are coming in my party " + friends[2]);
var friend = "Huzefa";
console.log("How are you bro today is my birthday and i arranged a party and you are invited. i hope you are coming in my party " + friend);
